services:
  ros-bag-recorder:
    image: ghcr.io/rosblox/ros-bag-recorder:humble
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    privileged: true
    ipc: host
    pid: host
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    volumes:
      - ~/rosblox/bags:/bags
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
